### ISSUE TITLE
trade and add liquidity button on token and pair pages are not redirecting correctly

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/analytics-dashboard-v2#41]
https://info.v2.jediswap.xyz/pool/0x508e297a3e1a9461c1f1a541dfff16c4a22e08238efe3b61c285c8da196ee3a

Currently, they are going to app.v2.jedi.. links. Instead, they should go to app.jedi... links

Also make sure to check they are going to the correct routes.

<img width="494" alt="image" src="https://github.com/jediswaplabs/analytics-dashboard-v2/assets/4688513/72af2ef7-1d1f-447b-9350-8a09ac1a6bb0">

**Comment by rohitgoyal** [comment]
Now they are giving this error when clicking on trade or add liquidity from the v2 dashboard. 
![image](https://github.com/jediswaplabs/analytics-dashboard-v2/assets/4688513/01255904-104a-4d1c-9e7e-3c960d269199)

**Comment by retroboydev** [comment]
fixed
