### ISSUE TITLE
Breadcrumb Navigation issue

### ISSUE THREAD

**Issue by rakakar** [jediswaplabs/analytics-dashboard-v2#88]
Clicking on "Home" in Home>Pools>Pool page should redirect me to the Overview(Home) page. Currently clicking on Pools and Home both are redirecting user to the Pools page.

https://github.com/jediswaplabs/analytics-dashboard-v2/assets/106336297/68254ae8-2899-4a37-974b-4d1a64d62f91

**Comment by iamoskvin** [comment]
Fixed
